### ISSUE TITLE
Для девушки с самым лучшим именем

### ISSUE THREAD

**Issue by VValentinesDay** [VValentinesDay/GitLessons#1]
Добавить, класс пряник
Добавить интерфей ITryGB, c методом string TraingLearn(). Реализация во второй задаче.

**Comment by VValentinesDay** [comment]
Реализация интерфесаю. Пусть пряник реализует интерфейс, таким образом: метод принимает число, возвращает строку в виде "Зачем мне {число} ???"

**Comment by Valentine-doc** [comment]
задача выполнена

**Comment by VValentinesDay** [comment]
Чётко
